version: '3.9'

volumes:
  next:

services:
  node:
    build:
      context: .
    container_name: testmate
    ports:
      - 3010:3010  # ホストの3010ポートをコンテナの3000ポートにマッピング
    volumes:
      - .:/works
      - next:/works/.next
